#-----
# telemetry
#-----

@ current acceleration in x, y, and z directions (in g's)
telemetry ACC_X: F32 id 0
telemetry ACC_Y: F32 id 1
telemetry ACC_Z: F32 id 2

@ current angular speed around x, y, and z axes (in degrees per second)
telemetry GYRO_X: F32 id 3
telemetry GYRO_Y: F32 id 4
telemetry GYRO_Z: F32 id 5

@ current magnetic field around x, y, and z axes (in micro Teslas)
telemetry MAG_X: F32 id 6
telemetry MAG_Y: F32 id 7
telemetry MAG_Z: F32 id 8